//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated manually.
//------------------------------------------------------------------------------

namespace EmployeeDirectory
{
    public partial class EmployeeDirectory
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.HiddenField hfEmployeeID;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPosition;

        protected global::System.Web.UI.WebControls.TextBox txtDepartment;

        protected global::System.Web.UI.WebControls.TextBox txtHireDate;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.Button btnClear;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.GridView gvEmployees;
    }
}